# Generated by Django 4.2.8 on 2026-01-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(verbose_name="Date d'emprunt")),
                ('due_date', models.DateTimeField(verbose_name="Date d'échéance")),
                ('return_date', models.DateTimeField(verbose_name='Date de retour')),
                ('status', models.CharField(max_length=20, verbose_name='Statut')),
                ('fine', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amende')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Archivé le')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.book', verbose_name='Livre')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': "Historique d'emprunt",
                'verbose_name_plural': 'Historique des emprunts',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('due_date', models.DateTimeField(verbose_name="Date d'échéance")),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNÉ', 'Retourné'), ('EN_RETARD', 'En retard')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Amende')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='library.book', verbose_name='Livre')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-loan_date'],
                'indexes': [models.Index(fields=['status', 'member'], name='loans_loan_status_67a70d_idx'), models.Index(fields=['loan_date'], name='loans_loan_loan_da_8d8a18_idx')],
            },
        ),
    ]
