# Generated by Django 4.2.8 on 2026-01-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_migrate_member_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0001_initial'),
        ('loans', '0002_demandeemprunt_demanderetour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.lecteur', verbose_name='Lecteur'),
        ),
        migrations.AlterField(
            model_name='loanhistory',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.lecteur', verbose_name='Lecteur'),
        ),
        migrations.AddField(
            model_name='demanderetour',
            name='emprunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan', verbose_name='Emprunt'),
        ),
        migrations.AddField(
            model_name='demanderetour',
            name='lecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retour', to='members.lecteur', verbose_name='Lecteur'),
        ),
        migrations.AddField(
            model_name='demanderetour',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='demandeemprunt',
            name='lecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_emprunt', to='members.lecteur', verbose_name='Lecteur'),
        ),
        migrations.AddField(
            model_name='demandeemprunt',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.book', verbose_name='Livre'),
        ),
        migrations.AddField(
            model_name='demandeemprunt',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
    ]
