# Generated by Django 4.2.8 on 2026-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('member_number', models.CharField(max_length=20, unique=True, verbose_name="Numéro d'adhésion")),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Remarques')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='members_mem_email_afed21_idx'), models.Index(fields=['member_number'], name='members_mem_member__425bc1_idx'), models.Index(fields=['status'], name='members_mem_status_734de0_idx')],
            },
        ),
    ]
