# Generated by Django 4.2.8 on 2026-01-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_lecteur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_alter_loan_member_alter_loanhistory_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='lecteur',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecteur', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur lié'),
        ),
        migrations.AddIndex(
            model_name='lecteur',
            index=models.Index(fields=['email'], name='members_lec_email_1b6e33_idx'),
        ),
        migrations.AddIndex(
            model_name='lecteur',
            index=models.Index(fields=['numero_abonnement'], name='members_lec_numero__728aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='lecteur',
            index=models.Index(fields=['statut'], name='members_lec_statut_91ca20_idx'),
        ),
    ]
